CREATE INDEX IF NOT EXISTS idx_assets_active_timeline_desc ON assets(timeline_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_timeline_asc ON assets(timeline_at ASC, id ASC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_imported_desc ON assets(imported_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_imported_asc ON assets(imported_at ASC, id ASC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_size_desc ON assets(size DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_size_asc ON assets(size ASC, id ASC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_filename_asc ON assets(lower(filename) ASC, id ASC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_filename_desc ON assets(lower(filename) DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_parent_timeline_desc ON assets(parent_rel_path, timeline_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_parent_filename_asc ON assets(parent_rel_path, lower(filename) ASC, id ASC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_parent_size_desc ON assets(parent_rel_path, size DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_assets_active_media_timeline_desc ON assets(media_type, timeline_at DESC, id DESC) WHERE deleted_at IS NULL;
