ALTER TABLE albums
  ADD COLUMN IF NOT EXISTS asset_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cover_asset_id BIGINT,
  ADD COLUMN IF NOT EXISTS stats_updated_at BIGINT NOT NULL DEFAULT 0;
